-- Formato de data em sql - GeTDATE DATA Atual 

SELECT CURRENT_TIMESTAMP
SELECT GETDATE()
SELECT GETUTCDATE()

-- Formato texto
SELECT DATENAME(WEEKDAY, GETDATE())
SELECT DATENAME(YEAR, GETDATE())

-- Formato Inteiro
SELECT YEAR(GETDATE())

-- Parte da Data
SELECT DATEPART(YEAR, GETDATE())