-- Formato de Data Avançado em SQL (DATEPART) - Avançado

USE Ecommerce

SELECT DATEPART(YEAR, GETDATE())
SELECT DATEPART(MONTH, GETDATE())
SELECT DATEPART(DAY, GETDATE())
SELECT DATEPART(HOUR, GETDATE())
SELECT DATEPART(MINUTE, GETDATE())
SELECT DATEPART(SECOND, GETDATE())
SELECT DATEPART(MILLISECOND, GETDATE())